// Auto-generated by Nuxt Architect CLI — do not edit manually.
// Run: app events:sync to regenerate.

import type { IEventBus } from './contracts/IEventBus.js'

export function registerEvents(_bus: IEventBus): void {
  // Listeners are registered here by app events:sync
}
